config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'concerts#index'

  get  '/search' => 'concerts#search'
  post '/search' => 'concerts#search'

  get '/top_ten' => 'concerts#top_ten'

  resources :concerts do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :concert, counter_cache: true

  validates :body, presence: true

  def self.persisted
    where.not(id: nil)
  end
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :band, presence: true
  validates :band, length: { maximum: 40 }

  validates :venue, presence: true
  validates :venue, length: { maximum: 40 }

  validates :city, presence: true
  validates :city, length: { maximum: 40 }

  validates :date, presence: true

  validates :price, presence: true
  validates :price, numericality: true

  validates :description, presence: true
  validates :description, length: { maximum: 300 }

  has_attached_file :poster, styles: { medium: "420x470>", thumb: "320x370>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/

  def self.concerts_today num=3
    where('date BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day).limit(num)
  end

  def self.concerts_later num=3
    where('date BETWEEN ? AND ?', DateTime.now.end_of_day, DateTime.now + 1.month).limit(num)
  end

  def self.search_by_price price
    where('price <= ?', price)
  end

  def self.popular_concerts
    all.order('comments_count DESC')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :concerts
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_concert

  def create
    unless current_user
      redirect_to new_user_session_path, :flash => { :danger => "Please sign in or sign up to comment." }
    else
      @comment = @concert.comments.build(comment_params)
      @comment.user = current_user

      if @comment.save
        flash[:success] = "Comment has been created successfully."
      else
        flash.now[:danger] = "Comment has not been created."
      end

      redirect_to concert_path(@concert)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
  
  def set_concert
    @concert = Concert.find(params[:concert_id])
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  def index
    @concerts_today = Concert.concerts_today(8)
    @concerts_later = Concert.concerts_later(4)
  end

  def show
    @comment = @concert.comments.build
  end

  def new
    @concert = Concert.new
  end

  def create
    @concert = current_user.concerts.build concert_params

    if @concert.save
      redirect_to @concert, flash: { success: "Concert has been saved successfully."}
    else
      render 'new', flash: { success: "Concert has not been saved."}
    end
  end

  def edit
    if @concert.user != current_user
      redirect_to root_path, :flash => { :danger => "You can only edit your own concerts." }
    end
  end

  def update
    if @concert.user != current_user
      redirect_to root_path, :flash => { :danger => "You can only edit your own concerts." }
    else
      if @concert.update(concert_params)
        redirect_to @concert, flash: { success: "Concert has been updated successfully."}
      else
        render 'edit', flash: { success: "Concert has not been updated."}
      end
    end
  end

  def destroy
    @concert.destroy
    redirect_to root_path, flash: { success: "Concert has been deleted successfully."}
  end

  def search
    @concerts = Concert.search_by_price(params[:price])

    render 'search'
  end

  def top_ten
    @concerts = Concert.popular_concerts
  end

  private

  def set_concert
    @concert = Concert.find(params[:id])
  end

  def concert_params
    params.require(:concert).permit(:band, :venue, :city, :date, :price, :description, :poster)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_concert_loop.html.haml
%article.concert
  .concert-body
    %h2
      =link_to concert_path(concert) do
        =concert.band
      %span.pull-right= number_to_currency(concert.price, unit: "€", separator: ",")
    =link_to concert_path(concert) do
      =image_tag concert.poster.url(:thumb)
    %p
      %i.fa.fa-map-marker.fa-fw
      = "#{concert.venue}, #{concert.city}"
    %p
      %i.fa.fa-calendar-o.fa-fw
      = concert.date

app/views/concerts/_form.html.haml
- if @concert.errors.any?
  #error_explanation
    %b
      = pluralize(@concert.errors.count, "error")
      prohibited this concert from being saved:
    %ul
      - @concert.errors.full_messages.each do |msg|
        %li= msg

= form_for @concert do |f|
  %fieldset
    =f.label :band
    =f.text_field :band
  %fieldset
    =f.label :venue
    =f.text_field :venue
  %fieldset
    =f.label :city
    =f.text_field :city
  %fieldset
    =f.label :date
    =f.datetime_local_field :date
  %fieldset
    =f.label :price
    =f.number_field :price
  %fieldset
    =f.label :description
    =f.text_area :description
  %fieldset
    = f.label :poster
    = f.file_field :poster

  %fieldset
    =f.submit

app/views/concerts/edit.html.haml
%h1 Edit concert

= render 'form'

app/views/concerts/index.html.haml
%section.concerts-today
  %h1.home-title Check today's concerts!
  .concerts-list
    - @concerts_today.each do |c|
      = render 'concert_loop', concert: c

%section.concerts-later
  %h1.home-title Later this month

  .concerts-list
    - @concerts_later.each do |c|
      = render 'concert_loop', concert: c

app/views/concerts/new.html.haml
%h1 New concert

= render 'form'

app/views/concerts/search.html.haml
%h1 Search concerts

%form{method: "POST", action: "/search"}
  %input{type: "number", name: "price", placeholder: "Maximum price..."}
  = hidden_field_tag :authenticity_token, form_authenticity_token
  %input{type: "submit"}

- if @concerts.present?
  - @concerts.each do |c|
    =c.band

app/views/concerts/show.html.haml
%section.concert.left
  .concert-body
    %h2
      =link_to concert_path(@concert) do
        =@concert.band
      %span.pull-right= number_to_currency(@concert.price, unit: "€", separator: ",")
    =link_to concert_path(@concert) do
      =image_tag @concert.poster.url(:thumb)
    %p
      %i.fa.fa-map-marker.fa-fw
      = "#{@concert.venue}, #{@concert.city}"
    %p
      %i.fa.fa-calendar-o.fa-fw
      = @concert.date

    %p
      =link_to "Edit", edit_concert_path(@concert)
      =link_to "Delete", concert_path(@concert), method: :delete, data: { confirm: "Are you sure?" }

%section.comments.left
  %h3
    =pluralize(@concert.comments.persisted.count, "Comment")

  %hr/
  - if @concert.comments.any?
    - @concert.comments.persisted.each do |comment|
      .comment-body
        = comment.body
      %i.comment-time
        \-
        = time_ago_in_words(comment.created_at)
        ago by #{comment.user.email}
      %hr/
  - else
    There are no comments to show.

  = form_for [@concert, @comment ] do |f|
    - if @comment.errors.any?
      .alert.alert-danger
        %b
          = pluralize(@comment.errors.count, "error")
          prohibited this concert from being saved:
          %ul
            - @comment.errors.full_messages.each do |msg|
              %li
                = msg
    %fieldset
      = f.label :body, 'New comment'
      = f.text_area :body, class: 'form-control', placeholder: 'Your comment'
    %fieldset
      = f.submit "Add comment", class: 'btn btn--blue btn--block'

app/views/concerts/top_ten.html.haml
%h1 Top 10 Concerts
  
- if @concerts.present?
  - @concerts.each do |c|
    =c.band

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ConcertNetwork
    %link{:href => "https://necolas.github.io/normalize.css/3.0.2/normalize.css", :rel => "stylesheet"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'shared/header'

    %main.container
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name}"}
          = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
      = yield

    = render 'shared/footer'

app/views/shared/_footer.html.haml
%footer.footer.container
  %p
    Copyright &copy; 2015 All Rights Reserved.
    %span.right
      Made with
      %span.red ♥
      by
      %a{:href => "http://twitter.com/@rubenmoya"} @rubenmoya

app/views/shared/_header.html.haml
%header.header.container
  %h1.logo
    =link_to root_path do
      %i.fa.fa-music
      Concert Network

  %nav.nav
    %ul
      %li=link_to "Concerts", root_path, class: "nav-item"
      %li=link_to "Search", search_path, class: "nav-item"

      - if user_signed_in?
        %li=link_to "Profile", edit_user_registration_path, class: "nav-item"
        %li=link_to "Log out", destroy_user_session_path, method: :delete,  class: "nav-item"
        %li=link_to "New concert", new_concert_path, class: "nav-item btn btn--blue"
      - else
        %li=link_to "Sign up", new_user_registration_path, class: "nav-item"
        %li=link_to "Sign in", new_user_session_path, class: "nav-item btn btn--blue"